"""The provider-agnostic incident reasoner interface.

One method, one input, one output::

    explanation = reasoner.reason(evidence)

Everything a provider needs is in the evidence; everything Sentinel needs back
is in the explanation. A provider may be a hosted API, a local model, a future
AMD-hosted endpoint, or a deterministic template — nothing outside this module
and :mod:`app.intelligence.providers` knows or cares which.

The deterministic core imports none of this. This module itself imports no
model SDK: providers are registered by name and their modules are imported
only when one is actually built, so ``import app.intelligence.reasoner`` never
pulls a vendor package into the process.
"""

from __future__ import annotations

import importlib
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional

from .evidence import IncidentEvidence
from .grounding import GroundingError, GroundingReport, assert_grounded, check_grounding
from .schema import IncidentExplanation


class ReasonerError(RuntimeError):
    """A provider could not produce a usable explanation."""


class ReasonerUnavailable(ReasonerError):
    """A provider exists but cannot run here (missing SDK, missing key)."""


class IncidentReasoner(ABC):
    """Turns deterministic evidence into a structured explanation.

    Implementations must not:

    * decide whether an incident exists — that decision arrived with the
      evidence;
    * alter, re-score or contradict any value in the evidence;
    * reach for information the evidence does not contain.
    """

    #: Short provider identity, e.g. ``"mock"`` or ``"anthropic"``.
    provider: str = "unknown"
    #: The specific model or template version behind this provider.
    model: str = "unknown"
    #: False when output is generated by deterministic code rather than a
    #: language model. Consumers label output with this, not with the name.
    is_language_model: bool = False

    @abstractmethod
    def reason(self, evidence: IncidentEvidence) -> IncidentExplanation:
        """Explain one incident. Never modifies ``evidence``."""
        raise NotImplementedError

    # ------------------------------------------------------------------
    @property
    def name(self) -> str:
        return self.provider

    def describe(self) -> str:
        kind = "language model" if self.is_language_model else "deterministic template"
        return f"{self.provider} / {self.model} ({kind})"

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<{type(self).__name__} {self.describe()}>"


@dataclass
class GroundedReasoner(IncidentReasoner):
    """Wraps a reasoner and refuses to pass ungrounded output through.

    The grounding check is not advice to the model, it is a gate on the
    output. With ``strict=True`` an ungrounded explanation raises rather than
    reaching a human; with ``strict=False`` it is returned but the report is
    kept on :attr:`last_report` so a caller can display the failures.
    """

    inner: IncidentReasoner
    strict: bool = True
    last_report: Optional[GroundingReport] = None

    def __post_init__(self) -> None:
        self.provider = self.inner.provider
        self.model = self.inner.model
        self.is_language_model = self.inner.is_language_model

    def reason(self, evidence: IncidentEvidence) -> IncidentExplanation:
        explanation = self.inner.reason(evidence)
        report = check_grounding(explanation, evidence)
        self.last_report = report
        if self.strict and not report.ok:
            raise GroundingError(report)
        return explanation


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------
#: name -> "module:attribute" of a zero-or-keyword-argument factory. Kept as
#: strings so registering a provider never imports its SDK.
_PROVIDERS: Dict[str, str] = {
    "mock": "app.intelligence.providers.mock:MockIncidentReasoner",
    "anthropic": "app.intelligence.providers.anthropic_claude:AnthropicIncidentReasoner",
}

_FACTORIES: Dict[str, Callable[..., IncidentReasoner]] = {}


def register_reasoner(
    name: str, factory: Callable[..., IncidentReasoner]
) -> None:
    """Register a reasoner factory under ``name`` (for plugins and tests)."""
    _FACTORIES[name] = factory


def available_reasoners() -> List[str]:
    """Every registered provider name, whether or not it can run here."""
    return sorted(set(_PROVIDERS) | set(_FACTORIES))


def build_reasoner(name: str = "mock", **kwargs: Any) -> IncidentReasoner:
    """Construct a reasoner by provider name.

    Raises :class:`ReasonerUnavailable` when the provider is known but its
    dependencies or credentials are missing — never a bare ``ImportError``,
    so a caller can tell "not installed" from "broken".
    """
    if name in _FACTORIES:
        return _FACTORIES[name](**kwargs)

    target = _PROVIDERS.get(name)
    if target is None:
        raise ReasonerError(
            f"unknown reasoner {name!r}; available: {', '.join(available_reasoners())}"
        )

    module_name, _, attribute = target.partition(":")
    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        raise ReasonerUnavailable(
            f"reasoner {name!r} is not available here: {exc}"
        ) from exc
    return getattr(module, attribute)(**kwargs)
